default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: wercker_test_development
test:
  <<: *default
  database: wercker_test_test
production:
  <<: *default
  database: wercker_test_production
